Add direnv and formatter for nix and shell
garnix-io/nix-tool-installer pull request #11
Opened 2023-12-08 21:31 UTC by jfroche

- Add direnv and formatter for nix and shell
- Fix formatting
- Upgrade to the latest nixpkgs stable

2023-12-13 21:11 UTC, soenkehahn requested changes
Overall this seems to make the flake file a lot more complicated for fairly little practical gain. Currently the only formatter that actually surfaces any issues is `shfmt`, I think. So I don't think I fully understand the motivation for this change.

Also, I find `treefmt` a bit opaque and underdocumented. Overall I think using it is not a terrible idea, but I would prefer to use something that is a little bit more accessible.

Also, this PR does multiple things at once and could be split up to discuss them separately. For example adding the `.envrc` file could be merged without further discussion.

2023-12-13 21:11 UTC, soenkehahn commented on flake.nix
> +              ];
Why are these disabled? These lint rules don't seem to be triggering any warnings.

2023-12-13 21:11 UTC, soenkehahn commented on flake.nix
> +            shellcheck.enable = true;
We already have a check running `shellcheck`, so I think now we're running it twice. We should remove one check.

2023-12-13 21:11 UTC, soenkehahn commented on flake.nix
> +  inputs.nixpkgs.url = "github:nixos/nixpkgs/23.11";
Can we put the update to 22.11 into a different PR, please? If we care enough about updating, that is.

2023-12-19 10:23 UTC, jfroche commented on flake.nix
> +              ];
Fixed in https://github.com/garnix-io/nix-tool-installer/pull/14

2023-12-19 10:24 UTC, jfroche commented on flake.nix
> +            shellcheck.enable = true;
Fixed in https://github.com/garnix-io/nix-tool-installer/pull/14

2023-12-19 10:24 UTC, jfroche commented on flake.nix
> +  inputs.nixpkgs.url = "github:nixos/nixpkgs/23.11";
Done here: https://github.com/garnix-io/nix-tool-installer/pull/13

2023-12-19 10:25 UTC, jfroche commented
PR has been split

2023-12-19 10:25 UTC, closed without merging