Use writeShellScriptBin to validate shell scripts
garnix-io/nix-tool-installer pull request #15
Opened 2023-12-19 10:22 UTC by jfroche

2023-12-19 19:47 UTC, soenkehahn requested changes
Could you describe a bit what this PR does and why? It looks like it switches some test scripts over from `writeScript` to `writeShellScriptBin`. Is that true? Does it change anything else? Also, why is that a good idea? The title says '... to validate ...'. Does `writeShellScriptBin` perform some kind of validation? I can't find documentation about that. Also, why is `writeShellScriptBin` better than `writeShellScript`?

2023-12-20 17:05 UTC, r-vdp commented
`writeShellScript{.Bin}` run the script in dry-run mode during the build to validate its syntax, meaning that you get a build-time error instead of a run-time error in case of syntax errors, which means that syntax errors get caught in CI instead of in production.

There's also `writeShellApplication` which also runs `shellcheck` on the scripts, doing even more validation. I usually prefer this where ever possible.

2023-12-20 17:48 UTC, soenkehahn commented
> writeShellScript{.Bin} run the script in dry-run mode during the build to validate its syntax

What's dry-run mode? Also, where is this behavior of `writeShellScriptBin` documented, if anywhere?

2023-12-20 18:06 UTC, r-vdp commented
> > writeShellScript{.Bin} run the script in dry-run mode during the build to validate its syntax
> 
> What's dry-run mode? Also, where is this behavior of `writeShellScriptBin` documented, if anywhere?

Mainly in the source code, I'm afraid: https://github.com/NixOS/nixpkgs/blob/3d19c43d6045093cc29ab251ad9919fe0296e6c5/pkgs/build-support/trivial-builders/default.nix#L280

The dry-run mode is a feature of bash where it basically parses the script and checks syntax, but doesn't actually run any commands.

And for `writeShellApplication`: https://github.com/NixOS/nixpkgs/blob/3d19c43d6045093cc29ab251ad9919fe0296e6c5/pkgs/build-support/trivial-builders/default.nix#L311

2023-12-22 14:56 UTC, jfroche commented
We can also use `writeShellApplication` to use shellcheck to also validate these scripts

2024-01-09 16:10 UTC, soenkehahn approved these changes
Apart from my comments LGTM.

2024-01-09 16:10 UTC, soenkehahn commented on flake.nix
> +              "${testFileServerScript}/bin/test-file-server";
Can we use `pkgs.lib.getExe` and inline `testFileServerScript`?

2024-01-09 16:10 UTC, soenkehahn commented on flake.nix
> +              "${bootVMScript}/bin/boot-vm";
Same here, maybe use `pkgs.lib.getExe` instead of string interpolation?

2024-01-09 16:10 UTC, soenkehahn commented on flake.nix
> +              "${sshVMScript}/bin/ssh-vm";
Same here.

2024-01-15 10:49 UTC, merged